## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file Iterazione0.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (Iterazione0.sagetex.sage) was *autogenerated* from Iterazione0.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('Iterazione0', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()

